name: Vercel Deploy

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: frontend/package.json

      - name: Install dependencies
        run: npm ci --no-audit --no-fund

      - name: Build
        run: npm run build

      # Preview deploy (non-main/master)
      - name: Pull env (preview)
        if: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master' }}
        run: npx vercel pull --yes --environment=preview --token ${{ secrets.VERCEL_TOKEN }}
      - name: Deploy (preview)
        if: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master' }}
        run: npx vercel deploy --prebuilt --token ${{ secrets.VERCEL_TOKEN }}

      # Production deploy (main/master)
      - name: Pull env (production)
        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}
        run: npx vercel pull --yes --environment=production --token ${{ secrets.VERCEL_TOKEN }}
      - name: Deploy (production)
        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}
        run: npx vercel deploy --prebuilt --prod --token ${{ secrets.VERCEL_TOKEN }}
